import MainLayout from "@/components/Layout/MainLayout";
import "./globals.css";

import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Ajay Ratha Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={roboto.className}>
        <div className="dark:bg dark:text-white flex flex-col h-full ">
          <MainLayout> {children}</MainLayout>
        </div>
      </body>
    </html>
  );
}
